### PR TITLE
CI: Update Ruby

### PR DESCRIPTION
**Pull request by ashie**
And shorten labels to make easy to read on GitHub.

Signed-off-by: Takuro Ashie <ashie@clear-code.com>

### CODE REVIEW

**Comment by ashie** [comment]
Failed on Ruby 3.1 and head for Windows:

https://github.com/fluent/fluent-plugin-windows-eventlog/runs/4962066485?check_suite_focus=true

```
C:/hostedtoolcache/windows/Ruby/3.1.0/x64/lib/ruby/gems/3.1.0/gems/fluentd-1.14.4/lib/fluent/plugin_helper/socket.rb:21:in `require': cannot load such file -- certstore (LoadError)
```

Because dependent gems on Windows aren't installed:
```
2022-01-27T05:53:04.5390041Z Fetching gem metadata from https://rubygems.org/......
2022-01-27T05:53:04.6911969Z Resolving dependencies...
2022-01-27T05:53:04.6967565Z Using rake 13.0.6
2022-01-27T05:53:04.7028984Z Using bundler 2.3.6
2022-01-27T05:53:04.7038451Z Fetching concurrent-ruby 1.1.9
2022-01-27T05:53:04.7041443Z Fetching cool.io 1.7.1
2022-01-27T05:53:04.8077950Z Installing cool.io 1.7.1 with native extensions
2022-01-27T05:53:04.8198541Z Installing concurrent-ruby 1.1.9
2022-01-27T05:53:05.2729090Z Fetching http_parser.rb 0.8.0
2022-01-27T05:53:05.3382590Z Installing http_parser.rb 0.8.0 with native extensions
2022-01-27T05:53:09.4791335Z Fetching msgpack 1.4.4
2022-01-27T05:53:09.5378131Z Installing msgpack 1.4.4 with native extensions
2022-01-27T05:53:34.8895959Z Fetching sigdump 0.2.4
2022-01-27T05:53:34.9429465Z Installing sigdump 0.2.4
2022-01-27T05:53:34.9987877Z Fetching strptime 0.2.5
2022-01-27T05:53:35.0527805Z Installing strptime 0.2.5 with native extensions
2022-01-27T05:53:44.6735579Z Fetching webrick 1.7.0
2022-01-27T05:53:44.7266374Z Installing webrick 1.7.0
2022-01-27T05:53:44.8361622Z Fetching yajl-ruby 1.4.1
2022-01-27T05:53:44.9393593Z Installing yajl-ruby 1.4.1 with native extensions
2022-01-27T05:53:45.7849084Z Using racc 1.6.0
2022-01-27T05:53:45.7849892Z Using power_assert 2.0.1
2022-01-27T05:53:45.7867837Z Fetching tzinfo 2.0.4
2022-01-27T05:53:45.8414037Z Installing tzinfo 2.0.4
2022-01-27T05:53:45.9730196Z Fetching serverengine 2.2.5
2022-01-27T05:53:46.0265663Z Installing serverengine 2.2.5
2022-01-27T05:53:46.1341129Z Fetching nokogiri 1.13.1 (x64-mingw-ucrt)
2022-01-27T05:53:46.3886267Z Installing nokogiri 1.13.1 (x64-mingw-ucrt)
2022-01-27T05:53:46.8080179Z Fetching test-unit 3.4.9
2022-01-27T05:53:46.8655514Z Installing test-unit 3.4.9
2022-01-27T05:53:46.9988063Z Fetching tzinfo-data 1.2021.5
2022-01-27T05:53:47.1028668Z Installing tzinfo-data 1.2021.5
2022-01-27T05:53:49.0654936Z Fetching fluentd 1.14.4
2022-01-27T05:53:49.1641868Z Installing fluentd 1.14.4
2022-01-27T05:53:50.3677084Z Using fluent-plugin-parser-winevt_xml 0.2.4 from source at `.`
2022-01-27T05:53:50.3765724Z Bundle complete! 4 Gemfile dependencies, 19 gems now installed.
2022-01-27T05:53:50.3766407Z Use `bundle info [gemname]` to see where a bundled gem is installed.
```

**Comment by ashie** [comment]
This is because `RUBY_PLATFORM` of RubyInstaller 3.1 is `x64-mingw-ucrt`.
Since we don't release fluentd's gem for such architecture, `ruby` platform is selected on installing it.

* ruby: https://rubygems.org/gems/fluentd/versions/1.14.4
* x64-mingw32: https://rubygems.org/gems/fluentd/versions/1.14.4-x64-mingw32
* x86-mingw32: https://rubygems.org/gems/fluentd/versions/1.14.4-x86-mingw32

It doesn't occur on Fluentd's unit test because it doesn't download fluentd's gem from RubyGems, use its Gemfile instead: https://github.com/fluent/fluentd/blob/e95132440bd0e3ae50f04bdf0f3ad525148270f6/fluentd.gemspec#L34-L43

**Comment by ashie** [comment]
I've released v1.14.4-x64-mingw-ucrt.
All tests are passed.

**Review by cosmo0920 — APPROVED** [review]
Yeah, the missing piece for ucrt is now fixed.

**Pull request merged**
