### PR TITLE
Relax required version of nokogiri

### PR DESCRIPTION
**Pull request by ashie**
nokogiri 1.14.0 has been released and it seems compatible too.

Signed-off-by: Takuro Ashie <ashie@clear-code.com>

### CODE REVIEW

**Review by cosmo0920 — APPROVED** [review]
:+1:

**Comment by ashie** [comment]
Thanks!

**Comment by cosmo0920** [comment]
This would be nice to be released as v0.8.3 for updating dependencies.

**Comment by ashie** [comment]
> This would be nice to be released as v0.8.3 for updating dependencies.

Done.

**Comment by cosmo0920** [comment]
Thanks!

**Pull request merged**
