### PR TITLE
Improve error handling and logging when failed to open Windows Event Log.

### PR DESCRIPTION
**Pull request by qingling128**
This helps investigation of https://github.com/fluent/fluent-plugin-windows-eventlog/issues/33.

### CODE REVIEW

**Comment by cosmo0920** [comment]
Thanks! :+1:
BTW, fluent organization requests `Signed-off-by` commit by [DCO](https://github.com/fluent/fluent-plugin-windows-eventlog/pull/34/checks?check_run_id=284194060).
Could you sign your commit?

**Comment by qingling128** [comment]
@cosmo0920 - Thanks for the heads up. Just signed it.

**Comment by qingling128** [comment]
@cosmo0920 Could you take a look at this one when you have a second?

**Comment by qingling128** [comment]
@cosmo0920 - Thanks! Regarding the next plugin release, do we know roughly when it would happen?

**Comment by cosmo0920** [comment]
Sorry for being late.
I've released this patch as v0.4.4.

BTW, we recommend to use in_windows_eventlog2 instead of in_windows_eventlog.
Is there any blocker to move using in_windows_eventlog2?

**Comment by qingling128** [comment]
@cosmo0920 - Thanks for the release! I only just realized there is a `in_windows_eventlog2` when I worked on this PR. Will give it a try for migration. Hopefully it goes smooth.

**Pull request merged**
